### ISSUE TITLE
Introducing Anshupriya!

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/partisan_dislocation#1]
Hey @drdeford,

Just hired Anshupriya -- a great MIDS student with strong CS background (but also interest in politics) -- to help us build a pip package from our dislocation scripts! 

@drdeford if you have a chance to throw your current scripts up here, that'd be super helpful for her. I think I have the `random_points_in_polygon` code in here already, but not sure I have the rest. 

@jrodden71 : Not sure if you need to watch this repo, but invited you in case you were interested. 

Also, I thought we'd outlined an API at one point, but now I can't find it. Do you remember where that was? We have too many repos for this project... I think it was 

- `make_representative_voter_points` : currently named `random_points_in_polygon` but that's dumb. Takes polygons with vote counts, makes a GeoDataFrame of representative points. 
- `calculate_voter_knn` : Get voter knn scores (pretty small function, but some people just want clustering scores to do things like what we did in my paper with Jonathan.
- `calculate_dislocation`: merge voter points with districts, calculate district partisan compositions, take difference with knn and return dislocation scores. 

@Anshupriya2694 : please share any questions you have here so @drdeford can help too!

**Comment by drdeford** [comment]
Hi @Anshupriya2694, nice to meet you! I will try to track the outline down, we definitely did sketch one somewhere.

**Comment by nickeubank** [comment]
Oh, also: you have full license to implement methods as you see fit. We are data monkeys (pretty good ones, I'd like to think, but monkeys nevertheless), so if something rankles your professional software engineering preferences, feel free to adjust. I think our only major preference is to vectorize wherever possible for performance. 

I also think we're agnostic on whether to go full OOP or functional, so do whatever you prefer. I think @drdeford and I are both comfortable with both paradigms.

**Comment by Anshupriya2694** [comment]
Hi, I am really excited about working on this project! I don't have any questions yet. I will update you soon as I have some!
