### ISSUE TITLE
wow... our calculate voter KNN has some issues

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/partisan_dislocation#14]
e.g. 

![image](https://user-images.githubusercontent.com/9683693/143785399-b3fea4e4-2dc1-4748-8b18-2562081f0129.png)

@drdeford any votes on what in particular is causing this mess? It's the `calculate_voter_knn` function. I'm currently working with a 7% sample from Ohio, which is big, obvi, but not insane... 

Maybe move to pygeos?

**Comment by nickeubank** [comment]
Up to 106GB. 

Not sure what would cause this. Either it's the spatial index itself (which thus must take FOREVER to grow), or something really weird is happening in the loop:

```python


    for index, row in voter_points.iterrows():

        # Extract self.
        neighbors = [i for i in ii[index] if i != index]
        if not len(neighbors) < len(ii[index]):
            raise ValueError(
                "You should never get this error. If you do, please post an issue on the github"
                " repository for this package at www.github.com/nickeubank/partisan_dislocation"
            )

        voter_points.at[index, f"knn_shr_{target_column}"] = (
            voter_points[target_column].iloc[neighbors].sum() / k
        )
```

Doesn't seem like it SHOULD though -- those lists of neighbors should be garbage collected every pass, right?

**Comment by nickeubank** [comment]
I could also add an "efficient" option that skips that filtering step

**Comment by nickeubank** [comment]
OK, how holding at 106gb. So maybe that is just the size of spatial index. 

![image](https://user-images.githubusercontent.com/9683693/143786286-35ca2417-3b69-46c3-83e1-0e00bc37ea7b.png)

**Comment by nickeubank** [comment]
OK, never went above 106, and stayed there a long time. Must be spatial index, which we're just pulling from library. So... there we go!

**Comment by drdeford** [comment]
Yikes! Maybe worth thinking in the medium/long term about implementing a project distance version of one of the kd trees. Or being more clever about exactly how much of the data we need by the time we get to that step.
