### ISSUE TITLE
Status / push recent commits?

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/partisan_dislocation#3]
Hey @anshupriya— how are things going? Would you mind pushing your recent commits when you have time?

**Comment by nickeubank** [comment]
@Anshupriya2694 sorry!

**Comment by Anshupriya2694** [comment]
@nickeubank, I had a few assignments to do last week. The tests are a work in progress and I need to do a little refactoring before I can push them. I will get it done by the end of the week.

**Comment by Anshupriya2694** [comment]
@nickeubank, I have added some tests as part of this commit : c9ad425ca44cc51388f50bc13af1becae9190ffb
