### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/partisan_dislocation#4]
@Anshupriya2694 added a [test suite](c9ad425ca44cc51388f50bc13af1becae9190ffb) for `random_points_in_polygon`. Thanks!

Are there unpushed edits to the repository at the moment @Anshupriya2694 ? 

If not, then I think we probably want to focus on the main code for the moment, since it seems you've gotten things organized for packaging and have started tests (unless you're a true test-driven development person and like to write your tests first, then code). 

A couple specific questions:

- The `random_points_in_polygon` method current seems to exist in three places: `partisan_dislocation/partisan_dislocation.py`, in `partisan_dislocation_pkg/partisan_dislocation/__init__.py`, and in `build/lib/partisan_dislocation/__init__.py`. We definitely want to only have one place where this all lives. 
- I think that codes is still just the initial copy-paste of some of our scripts with some docs added (e.g. those files have two methods named `random_points_in_polygon`, one the function we want people to use, and one a helper function). 
- There's also still that scratch `precincts = gdp.read_` in line 8 that won't run.

@Anshupriya2694 what would be your preferred way to move forward, or would you like a little more guidance? Also happy to jump on zoom if that'd be helpful!

**Comment by Anshupriya2694** [comment]
Hi @nickeubank,

- I have fixed the folder structure. When that folder was created initially, .gitignore was supposed to ignore a few additional files. That is sorted now.
- What kind of changes would you like me to make to the code? I was thinking of renaming the helper function. I just wasn't sure if that is what you wanted.
- I wanted to ask you which file that code is trying to read. When I looked at the data, there were several files with different extensions. I had commented it out for now since I didn't need it while testing the helper package. 

I also have an additional question. The code seems to be incorrect on line 54 as well. Do you know if that is just a typo?

**Comment by nickeubank** [comment]
Oh probably wrong. 

Sorry, I think life got ahead of all of us, so we never made a lot of progress early, but the code we have in there also needs work. We have scripts (used in one specific context to calculate our measure), but haven't generalized it. What's in there was just residuals of me mucking around. I'll push the rest of our scripts tomorrow and provide more concrete guidance on gathering (and if this suddenly seems like something you're not interested in, you can let me know then).

**Comment by nickeubank** [comment]
Oh! I take it back. They are in there! That's what's in the `original_scripts` folder -- that's the code in scripts we want packaged. The `partisan_dislocation.py` script you've bundled in was my very preliminary attempt to start outlining an API, but it was just that -- a very preliminary start. 

Please look it over the scripts, then let me know what questions you have!

**Comment by Anshupriya2694** [comment]
@nickeubank I am going through the code right now. I will let you know if I have any questions.

**Comment by Anshupriya2694** [comment]
Hi Nick, I cannot find the JSON files. The data pushed into this repository has 2008_presidential_precincy_count only. 
I cannot seem to locate the package dislocation_chain_utility. Could you please tell me what that is?

**Comment by nickeubank** [comment]
Hmmm will look tomorrow!

**Comment by nickeubank** [comment]
@Anshupriya2694 OK, adding that file now. 

@drdeford this is from the code you wrote but that we then set aside. Do you happen to still have the JSONs from the `dislocation_chain_utility.py` file somewhere?

**Comment by drdeford** [comment]
Hi! Hope you are both doing well! I'm sorry for not spotting this sooner, I forgot to `watch' the repo when it was created. 

I uploaded (what I think were) the .json and two shapefiles from dislocation_chain_utility.py here: people.csail.mit.edu/ddeford/PA_Dislocation_Data.zip

**Comment by nickeubank** [comment]
We should be fine -- she's just using them as example data. 

@Anshupriya2694 

So those are what was used in the initial scripts, but we don't need anything quite that fancy for the package. In those scripts, we calculated dislocation scores across a few thousand simulated district plans. In the future, what someone would do is loop over those district plans, and for each one call the functions in this package. 

So overall, this package should take in a shapefile with number of Democratic and Republican voters per polygon, and return a point shapefile where each point is the dislocation score for an individual representative voter. 

As noted in #1, I think this will require exposing the following functions to the user:

-  make_representative_voter_points : currently named random_points_in_polygon but that's dumb. Takes polygons with vote counts, makes a GeoDataFrame of representative points.
- calculate_voter_knn : Get voter knn scores (pretty small function, but some people just want clustering scores to do things like what we did in my paper with Jonathan.
- calculate_dislocation: merge voter points with districts, calculate district partisan compositions, take difference with knn and return dislocation scores.

Code to do all those things can be found in the `original_scripts` folder, but it's not nicely bundled / generalized. 

If any of that doesn't feel comfortable, let me know and we can schedule a zoom call?

**Comment by Anshupriya2694** [comment]
Hi Nick, I have a couple of doubts. Can we schedule a call for the 30th of May? I will be done with all the coursework by then.

**Comment by nickeubank** [comment]
30 of April? Sure! 10 am?

**Comment by Anshupriya2694** [comment]
Yep, 10 am works for me! Thank you!

**Comment by nickeubank** [comment]
@Anshupriya2694 Also, I sketched out the API in more detail by moving over relevant scripts into the `partisan_dislocation.py` file. It doesn't run, but should give you a better sense of what we're headed towards.

**Comment by Anshupriya2694** [comment]
Okay, I went over the scripts. I will schedule a call for tomorrow and send you mail. Is that okay?

**Comment by nickeubank** [comment]
I don’t quite follow – still want to talk at 10?

**Comment by Anshupriya2694** [comment]
The explanations above were very helpful. I have a couple of questions:
1. I can see you have mentioned that the file doesn't run. Can you tell me how to make it run? I won't be able to test it otherwise.
2. Is make_representative_voter_points the same as random_points_in_polygon? If yes, should I rename it and proceed?
3. Do you want me to test this as a package or the methods in the file directly?

**Comment by nickeubank** [comment]
I think there may be some confusion about the goals of this project. Regarding question 1, converting the application specific script code into a generalized set of functions _is_ the project — the tests are step two; step one is writing those methods. 

I’m happy to discuss goals, api parameters, etc if you’d like, but there’s unfortunately no simple trick to making the code run because the methods haven’t really been written. I don’t think writing them should take too long – all the functionality is an existing scrips, they just have to be generalized a little.

If that’s not something you feel comfortable doing, or would prefer not to do, just let me know.

**Comment by Anshupriya2694** [comment]
Ok, Thanks for the clarification.

**Comment by nickeubank** [comment]
Hey @Anshupriya2694 ! 

I just wanted to touch base on what your life is like over the next two weeks. I think if this isn't something you'll be able to address in the next couple weeks, I may hand it off to someone else -- the organizing for packaging has been really helpful, but I think it's time to get the package fully pulled together.

**Comment by Anshupriya2694** [comment]
Hi @nickeubank,

My internship is starting from Monday, and I will not be able to give as much time to this as I would have liked to. Based on my schedule it will be really challenging to get it done in the next 2 weeks. I understand that this has picked up urgency now, and will gladly share my experience with whoever takes this up.
If it not urgent, I can continue doing this on my own time during the next few weeks. ( My VISA status does not allow me to officially take up more than one job )

**Comment by nickeubank** [comment]
OK, thanks Anshupriya! I'm gonna see if Vivek wants to do some work on this, but if not I may circle back!

**Comment by viveksahukar** [comment]
I've uploaded my version of partisan dislocation with all the 3 functions debugged.
The script shows the output for the North Carolina subset of the dataframe.
In the last function calculate_dislocation: what input should I take for parameter: 'district'

**Comment by nickeubank** [comment]
Good call! Just pushed district shapefiles to `data`. Those are congressional boundaries. 

I think that code is least developed... we'll discuss in call.

**Comment by viveksahukar** [comment]
@nickeubank 
Hi Nick,
In the first joining of districts and voter_points in the command 
`districts.sjoin(voter_points[[dem_column]], how='left'`

the dem_column in voter_points is 'Dem' or 'KnnShrDem' (in my opinion it should be KnnShrDem) and what's the democrat count column in "districts" dataframe (couldn't identify from the column names)... 
Screenshots of both the data frames are attached for your reference.
![district](https://user-images.githubusercontent.com/27927203/85596304-99db2380-b617-11ea-9d27-86e1e8a449c7.PNG)
![voter_points](https://user-images.githubusercontent.com/27927203/85596307-9a73ba00-b617-11ea-8b9e-9fa3913e2c27.PNG)

Thanks!

**Comment by nickeubank** [comment]
There isn’t one. You calculate it from the representative voter points.
That’s why you were taking the average over “Dem”.

**Comment by viveksahukar** [comment]
@nickeubank 
When I'm taking intersection of geometry column for both district and NC (north Carolina) dataframe (obtained after calculating voter knn, it shows the following error
![district-crs](https://user-images.githubusercontent.com/27927203/85730877-03b30600-b6c8-11ea-977d-e6e820d58ced.PNG)
I have converted the NC dataframe to geopandas dataframe, but the crs attribute of the NC dataframe is empty (compared to district crs), that's why I think I'm getting error. 
I searched the web / forums but no luck. Any idea what I'm missing? 
When I originally read in the dataframe, I could get some value in crs attribute.

**Comment by viveksahukar** [comment]
Also I tried converting the NC dataframe to geopandas dataframe at the very beginning but the calculate knn score function gives the NaN values for KnnScore in `KnnShrDem` column.

Thanks!

**Comment by nickeubank** [comment]
When you create the `nc_gdf`, you also have to tell it what crs its using (i.e. what coordinate system created the points in nc_gdf. Assuming `nc_gdf` consists of points from `voter_points`, you'd want to run:

nc_gdf.crs = voter_points.crs
