### ISSUE TITLE
FYI: reorganized a little for publishing with flit

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/partisan_dislocation#7]
Using flit from this: https://realpython.com/pypi-publish-python-package/#publishing-to-pypi

So note that testing has moved into `tests`, and @viveksahukar 's notebook has moved up to the root directory outside the package folder.

**Comment by nickeubank** [comment]
@viveksahukar OK, did a bunch more work. Found a lot of problems, especially in `calculate_dislocation`, which had lots of hard-coded column names that don't work if you change the input data at all. You can find all my revisions [here](https://github.com/nickeubank/partisan_dislocation/commit/c76e844e19b0f6f264b1dbf928698b36928bd2d9)

**Comment by viveksahukar** [comment]
Hi Nick,
```
    def test_random_points_in_polygon_prob_test(self):
        df = gpd.GeoDataFrame({'dem': [1, 1, 0, 0, 0, 0], 'repub': [0, 0, 1, 1, 1, 1],
                              'geometry': [Polygon([(0, 0), (0, 0), (-2, 0)]), 
                                           Polygon([(0, 0), (0, 0), (-1, 0)]),
                                           Polygon([(0, 0), (0, 0), (1, 0)]),
                                           Polygon([(0, 0), (0, 0), (2, 0)]),
                                           Polygon([(0, 0), (0, 0), (3, 0)]),
                                           Polygon([(0, 0), (0, 0), (4, 0)])]},
                              crs='esri:102010')
        result = random_points_in_polygon(df, p=1, dem_vote_count='dem', repub_vote_count='repub')
        benchmark = pd.Series([1, 1, 0, 0, 0, 0], name='dem')
        pd.testing.assert_series_equal(result['dem'], benchmark)
```
I have created a points of dem, repub in a line as D, D, R, R, R, R. Since the polygon function takes 3 input arguments, I have repeated the origin (0, 0) as the 3rd coordinate.
When I ran this code, the result is not being created (the code is running forever).
The dataframe is created though.

Any thoughts on why this might be happening?

Thanks!

**Comment by nickeubank** [comment]
Yeah -- your polygons have zero area, so when it tries to create a point and see if it's inside the polygon, it never is. So it just keeps creating new candidate points. Try creating polygons with some area and I'll create an issue to raise an exception if this happens.￼￼￼

**Comment by viveksahukar** [comment]
after creating polygons with zero area, the test passed after some modification in random_points_in_polygon (some column name error was there).
now writing test for passing the result to next subsequent functions.

**Comment by nickeubank** [comment]
Great! Also just to doublecheck: you pulled before you started working,
right? You got all the updates I made Thursday and Friday?

**Comment by viveksahukar** [comment]
yeah... sure! I did that everytime in your class :)
for test district creation, they should be non-overlapping... right?

**Comment by nickeubank** [comment]
Great!

What do you mean by non-overlapping? There’s no harm in the same thing
being tested in multiple tests.

**Comment by viveksahukar** [comment]
Can't I access other functions outside the scope of the one which I'm testing?
```
    def test_calculate_voter_knn_simple_test(self):
        df = gpd.GeoDataFrame({'dem': [1, 1, 0, 0, 0, 0], 'rep': [0, 0, 1, 1, 1, 1], 
                               'geometry': [Polygon([(0, 1), (1, 0), (0, 0)]), 
                                            Polygon([(0, -1), (-1, 0), (0, 0)]),
                                            Polygon([(0, 1), (-1, 0), (0, 0)]),
                                            Polygon([(0, -1), (1, 0), (0, 0)]),
                                            Polygon([(1, 0), (1, 1), (0, 1)]),
                                            Polygon([(1, 0), (-1, -1), (0, -1)])]}, crs='esri:102010')
        df_random_points = random_points_in_polygon(df, p=1)
        df_voter_knn = calculate_voter_knn(df_random_points, k=3)
```
The test error is that "calculate_voter_knn" is not defined, but the function is well-written in the file.

**Comment by nickeubank** [comment]
Did you import it?

**Comment by viveksahukar** [comment]
Such a stupid mistake I made.. 
the dataframe passes through all functions now. I have pushed the updated test file on my branch.

![IMG_2822](https://user-images.githubusercontent.com/27927203/87863966-e8868f80-c92f-11ea-806c-a33d7e1396ce.jpg)

Could you restate in terms of the toy dataset (pic attached for clarity) how would I create a benchmark dataset for stochastic testing?
Thanks!
